packages:
  - .

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild

patchedDependencies:
  app-builder-lib@26.15.7: patches/app-builder-lib@26.15.7.patch
