export const DEFAULT_AGENT_TOOL_RESULT_COMPACTION_ENABLED = false
export const DEFAULT_AGENT_TOOL_RESULT_MAX_CHARACTERS = 16_000
export const MIN_AGENT_TOOL_RESULT_MAX_CHARACTERS = 2_000
export const MAX_AGENT_TOOL_RESULT_MAX_CHARACTERS = 100_000

export const DEFAULT_AGENT_DYNAMIC_TOOL_EXPOSURE_ENABLED = false
export const DEFAULT_AGENT_DYNAMIC_TOOL_LIMIT = 4
export const MIN_AGENT_DYNAMIC_TOOL_LIMIT = 1
export const MAX_AGENT_DYNAMIC_TOOL_LIMIT = 16

export const DEFAULT_AGENT_LAZY_SKILL_RESOURCES_ENABLED = false

export const DEFAULT_AGENT_CONTEXT_COMPACTION_ENABLED = false
export const DEFAULT_AGENT_CONTEXT_COMPACTION_THRESHOLD_PERCENT = 70
export const MIN_AGENT_CONTEXT_COMPACTION_THRESHOLD_PERCENT = 50
export const MAX_AGENT_CONTEXT_COMPACTION_THRESHOLD_PERCENT = 95
export const DEFAULT_AGENT_CONTEXT_COMPACTION_KEEP_RECENT_TURNS = 3
export const MIN_AGENT_CONTEXT_COMPACTION_KEEP_RECENT_TURNS = 1
export const MAX_AGENT_CONTEXT_COMPACTION_KEEP_RECENT_TURNS = 10

export const DEFAULT_AGENT_PROVIDER_CONTEXT_OPTIMIZATION_MODE = 'off' as const
