export const IPC_CHANNELS = {
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  providersList: 'providers:list',
  providersUpsert: 'providers:upsert',
  providersRemove: 'providers:remove',
  providersTest: 'providers:test',
  modelsList: 'models:list',
  modelsUpsert: 'models:upsert',
  modelsRemove: 'models:remove',
  modelsDiscover: 'models:discover',
  skillsList: 'skills:list',
  skillsUpsert: 'skills:upsert',
  skillsRemove: 'skills:remove',
  skillsToggle: 'skills:toggle',
  skillsResetDefaults: 'skills:reset-defaults',
  conversationsList: 'conversations:list',
  conversationsGet: 'conversations:get',
  conversationsSave: 'conversations:save',
  conversationsRemove: 'conversations:remove',
  dataClearConversations: 'data:clear-conversations',
  chatStart: 'chat:start',
  chatCancel: 'chat:cancel',
  chatEvent: 'chat:event',
  appGetInfo: 'app:get-info',
} as const
