name: Quality Checks

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js and pnpm
        uses: pnpm/setup@v2
        with:
          version: 11.24.0
          runtime: node@24
          cache: true
          install: false

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Quality Checks
        run: pnpm check
